-- Send staging data to production database. 
-- In the production database, we will update all 'active' records and insert all new records (listed within the last 7 days) 

MERGE INTO HOUSING_MARKET_PRODUCTION.PUBLIC."Property_Sale_Listings" AS TARGET
USING (
    SELECT * 
    FROM HOUSING_MARKET_STAGING.PUBLIC.PROPERTY_SALE_LISTINGS
    WHERE 
		  (status = 'Active' OR days_on_market < 7)
		AND 
			city IN ('Silver Spring', 'Rockville', 'Bethesda', 'Hyattsville', 'Chevy Chase', 
                   'Takoma Park', 'College Park', 'Riverdale', 'Potomac', 'Brentwood', 
                   'Kensington', 'Mount Rainier', 'University Park', 'Glenn Dale', 
                   'Gaithersburg', 'North Bethesda', 'Bowie', 'Garrett Park', 'Cabin John', 'Glen Echo')

) AS SOURCE
ON TARGET.ID = SOURCE.ID

WHEN MATCHED THEN 
    UPDATE SET 
        TARGET.BATHROOMS = SOURCE.BATHROOMS,
        TARGET.BEDROOMS = SOURCE.BEDROOMS,
        TARGET.PRICE = SOURCE.PRICE,
        TARGET.SQUARE_FOOTAGE = SOURCE.SQUARE_FOOTAGE,
        TARGET.COUNTY = SOURCE.COUNTY,
        TARGET.PROPERTY_TYPE = SOURCE.PROPERTY_TYPE,
        TARGET.ADDRESS_LINE_1 = SOURCE.ADDRESS_LINE_1,
        TARGET.CITY = SOURCE.CITY,
        TARGET.STATE = SOURCE.STATE,
        TARGET.ZIP_CODE = SOURCE.ZIP_CODE,
        TARGET.FORMATTED_ADDRESS = SOURCE.FORMATTED_ADDRESS,
        TARGET.LAST_SEEN = SOURCE.LAST_SEEN,
        TARGET.LISTED_DATE = SOURCE.LISTED_DATE,
        TARGET.STATUS = SOURCE.STATUS,
        TARGET.REMOVED_DATE = SOURCE.REMOVED_DATE,
        TARGET.DAYS_ON_MARKET = SOURCE.DAYS_ON_MARKET,
        TARGET.CREATED_DATE = SOURCE.CREATED_DATE,
        TARGET.LOT_SIZE = SOURCE.LOT_SIZE,
        TARGET.YEAR_BUILT = SOURCE.YEAR_BUILT,
        TARGET.LATITUDE = SOURCE.LATITUDE,
        TARGET.LONGITUDE = SOURCE.LONGITUDE

WHEN NOT MATCHED THEN 
    INSERT (
        "ID", "BATHROOMS", "BEDROOMS", "PRICE", "SQUARE_FOOTAGE", "COUNTY",
        "PROPERTY_TYPE", "ADDRESS_LINE_1", "CITY", "STATE", "ZIP_CODE",
        "FORMATTED_ADDRESS", "LAST_SEEN", "LISTED_DATE", "STATUS", "REMOVED_DATE",
        "DAYS_ON_MARKET", "CREATED_DATE", "LOT_SIZE", "YEAR_BUILT", "LATITUDE", "LONGITUDE"
    ) 
    VALUES (
        SOURCE."ID", SOURCE."BATHROOMS", SOURCE."BEDROOMS", SOURCE."PRICE", SOURCE."SQUARE_FOOTAGE", SOURCE."COUNTY",
        SOURCE."PROPERTY_TYPE", SOURCE."ADDRESS_LINE_1", SOURCE."CITY", SOURCE."STATE", SOURCE."ZIP_CODE",
        SOURCE."FORMATTED_ADDRESS", SOURCE."LAST_SEEN", SOURCE."LISTED_DATE", SOURCE."STATUS", SOURCE."REMOVED_DATE",
        SOURCE."DAYS_ON_MARKET", SOURCE."CREATED_DATE", SOURCE."LOT_SIZE", SOURCE."YEAR_BUILT", SOURCE."LATITUDE", SOURCE."LONGITUDE"
    );
